name: Make Public

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest    
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: public
        FOLDER: public
        HUGO_VERSION: 0.57.2
        BUILD_SCRIPT: |
          wget https://github.com/gohugoio/hugo/releases/download/v0.62.1/hugo_${HUGO_VERSION}_Linux-64bit.deb
          wget https://github.com/gohugoio/hugo/releases/download/v0.62.1/hugo_extended_${HUGO_VERSION}_Linux-64bit.deb
          dpkg -i hugo_${HUGO_VERSION}_Linux-64bit.deb
          dpkg -i hugo_extended_${HUGO_VERSION}_Linux-64bit.deb
          git submodule update --init
          hugo -v
